"""address

Revision ID: 21858432e8fe
Revises: 
Create Date: 2026-01-20 00:06:51.191148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21858432e8fe'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('address_line1', sa.String(length=255), nullable=False),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('address_line3', sa.String(length=255), nullable=True),
    sa.Column('city_locality', sa.String(length=100), nullable=False),
    sa.Column('state_province', sa.String(length=100), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('address_residential_indicator', sa.Enum('UNKNOWN', 'YES', 'NO', name='residentialindicator'), nullable=False),
    sa.Column('matched_address_line1', sa.String(length=255), nullable=True),
    sa.Column('matched_address_line2', sa.String(length=255), nullable=True),
    sa.Column('matched_address_line3', sa.String(length=255), nullable=True),
    sa.Column('matched_city_locality', sa.String(length=100), nullable=True),
    sa.Column('matched_state_province', sa.String(length=100), nullable=True),
    sa.Column('matched_postal_code', sa.String(length=20), nullable=True),
    sa.Column('matched_country_code', sa.String(length=2), nullable=True),
    sa.Column('status', sa.Enum('UNVERIFIED', 'VERIFIED', 'WARNING', 'ERROR', name='addressstatus'), nullable=False),
    sa.Column('validation_messages', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('addresses')
    # ### end Alembic commands ###
